//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtutOtomasyonu_KayaEğitimKurumları__ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtutSalonu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EtutSalonu()
        {
            this.SayisalEtutSalonu = new HashSet<SayisalEtutSalonu>();
            this.SozelEtutSalonu = new HashSet<SozelEtutSalonu>();
            this.BilisimEtutSalonu = new HashSet<BilisimEtutSalonu>();
        }
    
        public int SalonNo { get; set; }
        public string SalonAdi { get; set; }
        public string KullaniciNo { get; set; }
        public int KullanicilarKullaniciNo { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SayisalEtutSalonu> SayisalEtutSalonu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SozelEtutSalonu> SozelEtutSalonu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilisimEtutSalonu> BilisimEtutSalonu { get; set; }
    }
}
