//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtutOtomasyonu_KayaEğitimKurumları__ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SayisalEtutSalonu
    {
        public int SaySalonNo { get; set; }
        public int Tarih { get; set; }
        public int Saat { get; set; }
        public int SalonNo { get; set; }
        public int EtutSalonuSalonNo { get; set; }
    
        public virtual EtutSalonu EtutSalonu { get; set; }
    }
}
